version: '2.2'
services:
  cache:
    container_name: cache
    hostname: cache
    image: redis:latest
    ports:
      - '6379:6379'
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    build: .
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
  db:
    container_name: formules
    hostname: formules
    image: postgres:11.1
    environment:
      POSTGRES_USER: filit
      POSTGRES_PASSWORD: filit
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  app:
    image: calcutator
    build:
      context: .
    container_name: calcutator
    depends_on:
      - db
    environment:
      PGSQL_URL: jdbc:postgresql://db:5432/postgres