server:
#  servlet.context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PGSQL_URL:jdbc:postgresql://127.0.0.1:5432/postgres}
    username: ${PGSQL_USERNAME:filit}
    password: ${PGSQL_PASSWORD:filit}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true

cllc:
  formulas-loading:
    enabled: true
    scheduler:
      fixedRate: ${CLLC_FORMULAS_LOAD_EVERYMIN:15}
      cron: ${CLLC_FORMULAS_LOAD_ON}
